### ISSUE TITLE
Add checks to verify that we don't have multiple ways to inject field values

### ISSUE THREAD

**Issue by andrewcox** [facebook/swift#131]
As of a few days ago, if you add a @ThriftField-annotated public field, a @ThriftConstructor constructor with a @ThriftField-annotated parameter for setting that same field, and a @ThriftField-annotated setter method for setting that field, swift will call ALL of them when reading the type off the wire (assuming that field is read from the wire).

We should add checks to the metadata builders that there is only one annotated way to set each field. It's still ok for a class to have a two ways to actually set the method, as long as they aren't annotated.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
