### ISSUE TITLE
Cannot use guice to inject two ThriftServers

### ISSUE THREAD

**Issue by andrewcox** [facebook/swift#143]
Because ThriftServer and ThriftServiceProcessor are bound as singletons, it is difficult to create two swift servers (listening on two different ports) via guice.

We should either come up with some module changes that make this feasible, or else add instructions recommending child injectors for this.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
