### ISSUE TITLE
Add Server Side stats and expose them via jmx

### ISSUE THREAD

**Issue by rshroff** [facebook/swift#157]
There are many server side metrics which can be potentially used to debug issues and also fine tune the server configuration. For example, metrics like
*call queue length
*wait time in queue
*num worker threads busy/idle 

Would be useful to identify the bottlenecks on the server side.

Also, AFAIK, Guice is the recommended way of capturing the stats. Apart from Guice, there should be easier via to capture the stats and expose them via JMX.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
