### ISSUE TITLE
Need a way to specify a field is optional in swift

### ISSUE THREAD

**Issue by andrewcox** [facebook/swift#162]
@ThriftField annotation could have an "optional" field, and if this is set, the swift->thrift generator should apply the optional attribute to the field.

**Comment by dain** [comment]
@andrewcox is this implemented?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
