### ISSUE TITLE
Need to handle the case where a sync call is made on the channel's I/O thread

### ISSUE THREAD

**Issue by andrewcox** [facebook/swift#173]
Because connecting returns a future, a common pattern you might try to use is to add a future listener waiting for the successful connect, and in that listener make a thrift call.

However, if you make a blocking thrift call, you will deadlock the netty I/O thread.

We should check this before starting blocking thrift calls, and throw an exception in this case.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
