### ISSUE TITLE
ThriftServiceProcessor says it isn't production ready

### ISSUE THREAD

**Issue by Randgalt** [facebook/swift#193]
The commend at the top of ThriftServiceProcessor says "This should only be considered an example, and is not production ready. For example, this class makes assumptions about the thrift id of method parameters, and does not support Thrift exceptions properly." Per David Phillips it's used in production. So, the comment should be updated.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
