### ISSUE TITLE
Reject requests if the Memory used by requests is too high. 

### ISSUE THREAD

**Issue by manukranthk** [facebook/swift#205]
The current swift server does not have throttling of requests based on the amount of space consumed by the currently ongoing requests. We should be able to provide a limit for the amount of space that can be occupied by the currently ongoing requests. In that case, if the server can reject the client request, we can catch it as a TTransportException on the client and retry with timeouts.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
