### ISSUE TITLE
Container data structures backed by byte buffers.

### ISSUE THREAD

**Issue by manukranthk** [facebook/swift#208]
In scenarios where we have a list of containers, where each container holds a byte buffer. The byte buffers of individual containers can be backed by a single byte array. This would significantly cut down small object creation in large throughput systems by almost a factor of 2.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
