### ISSUE TITLE
swift-generator cannot handle map constants that have enum key types

### ISSUE THREAD

**Issue by andrewcox** [facebook/swift#209]

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by x1957** [comment]
Has this issue been fixed?

**Comment by lukenels** [comment]
While this doesn't pertain to this project in particular, I've been working on porting the swift generator back to https://github.com/facebook/fbthrift and plan on fixing this issue there.
