### ISSUE TITLE
Clients and codecs should be validated transitively at injector creation

### ISSUE THREAD

**Issue by electrum** [facebook/swift#217]
When binding a client or codec, Swift should validate the client or codec and all of its dependent codecs when the injector is created. Currently, this seems to happen lazily at runtime, so an infrequently called method or used field won't be detected until it is already in production (assuming it is not explicitly covered by tests).

This will make it much easier to get full test coverage of all structs and catch problems like missing the new requirement that classes be final. It should be enough for a test to simply bind the client.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
