### ISSUE TITLE
Need method to add 3rd party types to catalog for swift2thrift

### ISSUE THREAD

**Issue by allComputableThings** [facebook/swift#237]
I'd like make it easy to taken existing service interfaces (dealing with some third party beans types), and make them available as a swift service and generate thrift clients via swift2thrift.

A number of serialization frameworks provide the ability to serialize types without adding requiring ownership of the source code for that types (e.g. Jackson support serialization of beans) -- so, I'm working on a method to register types prior to:
- running thrift2swift
- creating a swift service

I'm looking at providing an alternate SwiftStructMetaDataBuilder to do this. It will:
- work for bean-style classes
- work for classes with public fields
- work for scala-style fields
- enforce a consistent (alphabetical) ID ordering of these
- warn about future-proofing (since this classes are unannotated thrift's ID bases future proofing goes out of the window)

Does this look the reasonable approach (adding a SwiftStructMetaDataBuilder, using it to generate a ThriftType and registering the type with the catalog)?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
