### ISSUE TITLE
Support from multiplexed client with ThriftClientManager

### ISSUE THREAD

**Issue by stuz5000** [facebook/swift#245]
Is this already supported? Can I produce a protocol object I can wrap with a TMultiplexedProcessor?

**Comment by stuz5000** [comment]
*bump*

Is this already possible?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
