### ISSUE TITLE
Any plan for swift2thrift maven plugin?

### ISSUE THREAD

**Issue by kdlan** [facebook/swift#246]
Is there any plan for swift2thrift maven plugin? Just like the swift maven plugin, generate IDL file from Swift annotations.  Or If I make a pull request for this feature, is there any instructions I should follow?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
