### ISSUE TITLE
Generated .thrift is not valid?

### ISSUE THREAD

**Issue by stuz5000** [facebook/swift#248]
If I use a generated .thrift file starting with 
```
namespace java.swift com.facebook.swift.service.annotations
```
as (https://github.com/facebook/swift/tree/master/swift2thrift-generator-cli), and run
```
thrift -r  --gen py test.thrift
```
I get:
```
[WARNING:/tmp/test.thrift:1] java generator does not accept 'swift' as sub-namespace!
```

(where:  thrift --version is 0.9.2)

What's going on here?

**Comment by alandau** [comment]
It's just a warning, safe to ignore. Regular Thrift doesn't know about the swift namespace, but swift-generator uses it to generate the correct siwft package name.
