### ISSUE TITLE
Support for Future of Future for Async Services

### ISSUE THREAD

**Issue by supercharger** [facebook/swift#271]
Let's say a Client is calling ServiceA which is in turn calling ServiceB. The method calls in ServiceA and ServiceB are Async by using ListenableFutures.

In the ServiceA method call "doSomeWorkA", I don't want to wait on the Future returned by ServiceB, so It won't impact the throughput. Please note that I need to construct ProcessedResultA from ProcessedResultB

Can you help on how to do this.

```java
@ThriftService
public interface ServiceA  {
    // Calls ServiceB
   @ThriftMethod
    public ListenableFuture<ProcessedResultA> doSomeWorkA(String input);
}

@ThriftService
public interface ServiceB {
   @ThriftMethod
    public ListenableFuture<ProcessedResultB> doSomeWorkB(String input);
}
```

**Comment by x1957** [comment]
You can use Futures.transform()

http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/util/concurrent/Futures.html#transform(com.google.common.util.concurrent.ListenableFuture,%20com.google.common.util.concurrent.AsyncFunction)

**Comment by supercharger** [comment]
I will try this, Thanks!!
