### ISSUE TITLE
Avoid io.airlift.log.Logger and use slf4j

### ISSUE THREAD

**Issue by Treydone** [facebook/swift#287]
The logging framework should be configurable and must not rely on the java.util.logging classes. SLF4J is IMHO a best candidate for this.

Classes impacted:
com.facebook.swift.service.ThriftServiceProcessor

Files impacted:
pom.xml

**Comment by electrum** [comment]
This reasoning is backwards. JUL is built into the JDK and thus is the best choice, especially due to versioning, class loaders, etc. If the application using Swift wants to use SLF4J (or more accurately, a backend for it), then the application may install the bridge from JUL to SLF4J.

**Comment by electrum** [comment]
We actually used to use SLF4J, but switched to JUL to avoid issues with class loaders: https://github.com/airlift/airlift/commit/5ff3c401da15385f1cab0f54f116a2c12d38f1dd
