### ISSUE TITLE
 swift2thrift generate thrift IDL.why not have required or optional in fields of struct。

### ISSUE THREAD

**Issue by dikewen** [facebook/swift#311]
I try swift2thrift-generator-cli-0.12.0-standalone.jar,swift2thrift-generator-cli-0.14.1-standalone.jar,swift2thrift-generator-cli-0.14.2-standalone.jar,they all have the problem,can you explain why,or what i can  do to generate "Field Requiredness".

ps : @ThriftField annotaion required attribute does not work

**Comment by alandau** [comment]
What are you trying to do exactly, and what is the problem? Please post source code and the commands you use that show the problem.

**Comment by andrewcox** [comment]
@dikewen I'll close this for now, but please feel free to reopen when you have some code demonstrating this so we can investigate.
