### ISSUE TITLE
ThriftMethodProcessor : Set default value of paramter even its requiredness is OPTIONAL;

### ISSUE THREAD

**Issue by xiemeilong** [facebook/swift#334]
Don't set default value when the parameter is OPTIONAL.  and I think should  not set default value when its class is java.lang.Long and other null able number.

**Comment by bitgaoshu** [comment]
In my opinion, as the java-doc states, the ```enum Requiredness``` indicates the behavior for a [field](https://github.com/facebook/swift/blob/master/swift-annotations/src/main/java/com/facebook/swift/codec/ThriftField.java).then it not works for a parameter.
