### ISSUE TITLE
java.lang.NullPointerException: value is null

### ISSUE THREAD

**Issue by johje349** [facebook/swift#338]
When returning a List<String> containing some null's we get the following error:
java.lang.NullPointerException: value is null

Is this a limitation in swift or thrift? Any plans on supporting it?

**Comment by m-hogue** [comment]
Thrift doesn't support sending nulls over the wire. You need to either throw an exception (which needs to be [annotated on your services](https://github.com/facebook/swift/tree/master/swift-service)) or wrap the result in something.
