### ISSUE TITLE
Boolean and other wrappers not properly being set to `null`

### ISSUE THREAD

**Issue by filpano** [facebook/swift#340]
I have a Swift Thrift interface which has several `String` and some `Boolean` parameters (not a `@ThriftStruct`). 

I read in the `@ThriftField` [Javadocs lines 77-83](https://github.com/facebook/swift/blob/master/swift-annotations/src/main/java/com/facebook/swift/codec/ThriftField.java) that you should be able to use wrappers for primitives.

Together with setting the parameters as `@ThriftField(requiredness = Requiredness.OPTIONAL)`, this should have actually enabled me to also get a `null` value on the receiving side. It works with `String` - but not with `Boolean`, which always has a default value of `false` even though I do not set it.

Is this a known issue? Is there a workaround?

**Comment by SystemHan** [comment]
I have this problem, too.And I solved the problem by modifying the source code.
In my understanding that the source code said the base type which is the parameter of method will set a default value by swift.

**Comment by lijiwen** [comment]
how to fix it？？？

**Comment by SystemHan** [comment]
see https://github.com/facebook/swift/pull/345

**Comment by lijiwen** [comment]
thanks @SystemHan
