### ISSUE TITLE
Updating netty version 4

### ISSUE THREAD

**Issue by gkamgang** [facebook/swift#359]
Hi,

First thanks for your  library, it made our  thrift code  quite readable and maintainable.
The last swift version uses netty 3.10.5. 
This  netty version has a bug with the DNS resolver which leads to an infinite cache of DNS resolved IP (no expirtation time). This makes quite annoying to use it with some dynamic domain name where the corresponding IP may change anytime. 

Did  anyone experienced the same problem ?
It seems that the bug is corrected with netty 4. So may I asked if you plan to update netty with swift ?
If not, we may have to create a fork for it, how hard  will it take to update nett4 ?
Otherwise, we  might only have the choice to revert back to use plain thrift.

Thanks,

**Comment by dain** [comment]
If you are specifically looking for Netty 4, take a look at Drift (https://github.com/airlift/drift).  This is a full rewrite of the protocol using Netty 4.  The client and server APIs should be familiar, but have some differences.  Specifically, Drift has integrated support for address selection, retries, and many more items that in the past were handled external to the RPC clients.  The Drift project is mainly written for Presto, but should generally work for most use cases.

**Comment by panchenko** [comment]
Do I understand it correctly that this repo is frozen?
Adding a link to Drift in README would be helpful then.
