### ISSUE TITLE
Make swift-codec compatible with lombok beans

### ISSUE THREAD

**Issue by anomalizer** [facebook/swift#61]
[lombok](http://projectlombok.org/features/GetterSetter.html) lets you auto-generate setters & getters for beans. The current _@ThriftField_ annotation can be attached to either an accessor method or a public variable.

It would be nice if we could attach this to the underlying private member of the bean. This would also make the Immutable object instances have lesser code

**Comment by cn-percy-wang** [comment]
I think @anomalizer 's mean is want Swift support @ThriftField to be attached to private field which can be accessed from getter and setter.

**Comment by andrewcox** [comment]
Swift wouldn't know how to serialize/deserialize the object instances with only private fields. If lombok transforms these into types with setters/getters, perhaps it needs some way to move the annotations from the private fields to these setters and getters, so it generates beans compatible with frameworks like swift.

In theory, swift could propagate annotations from fields onto the setters/getters of the same type, to make this work automatically, but someone else just asked me a week or two ago how they could have both a builder-type constructor and field setters for the same object, and my suggestion was not to either not annotate the setters, or not annotate the builder constructor. If we propagated the annotations automatically by name, we'd break that scenario.

**Comment by andrewcox** [comment]
** "onto the setters/getters of the same type" => "onto the setters/getters of the same name"

**Comment by cn-percy-wang** [comment]
In theory, just support annotate the getter is better, because this can be overrideed. But many people just like put all annotations on filed, and just generate getters and setters by ide or other tool, and this make the code more readable (no need to find getters or setters in the long listed code).  So, can we just find the annotation in a priority of field (no matter private or public) > getter > builder ?
